<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>229faf65-c356-4ed3-ba33-dd5faa4a33a7</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_qa_actions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[2]/div[1]/div[1]/div[4]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[9]/td[16]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[role="row"]:nth-child(9) #qa-actions</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'qa-actions')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>qa-actions</value>
        <webElementGuid>91efc7d3-75bd-4ce0-9cef-871f54231e4c</webElementGuid>
    </webElementProperties>
</WebElementEntity>