<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fb6ca26a-e23d-4bf2-bacb-a246e7b417c1</elementGuidId>
    <imagePath></imagePath>
    <name>button_qa_next</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/form[1]/div[2]/button[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#qa-next</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'qa-next') and equals(@text,'NEXT STEP')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>qa-next</value>
        <webElementGuid>9c2f4cfd-80ba-4962-beb4-6111e0549940</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>NEXT STEP</value>
        <webElementGuid>9c2f4cfd-80ba-4962-beb4-6111e0549940</webElementGuid>
    </webElementProperties>
</WebElementEntity>