<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0b91b850-ab1b-4d60-bcd5-a6345252637a</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_qa_edit_group</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="dropdown-menu\\ dropdown-menu-fit\\ dropdown-menu-right\\ show"] #qa-edit-group</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'qa-edit-group') and equals(@text,'\u0642\u0627\u0626\u0645\u0629 \u0627\u0644\u0645\u0639\u062a\u0645\u0631\u064a\u0646')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>qa-edit-group</value>
        <webElementGuid>ea5a58e0-bd3a-464a-a9bb-588338e6d0e1</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>قائمة المعتمرين</value>
        <webElementGuid>ea5a58e0-bd3a-464a-a9bb-588338e6d0e1</webElementGuid>
    </webElementProperties>
</WebElementEntity>