<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3d677772-a79f-4691-a041-d34c66f3ec30</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_qa_actions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[2]/div[1]/div[1]/div[4]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[1]/td[16]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="odd"] #qa-actions</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'qa-actions')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>qa-actions</value>
        <webElementGuid>9c2f4cfd-80ba-4962-beb4-6111e0549940</webElementGuid>
    </webElementProperties>
</WebElementEntity>