<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e453a589-e563-4a51-a169-3c00d7506aa8</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\\ btn-primary"]:nth-child(3)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'\u0627\u0644\u0645\u0639\u062a\u0645\u0631\u064a\u0646 \u0627\u0644\u0630\u064a\u0646 \u0644\u0645 \u064a\u0635\u062f\u0631 \u0644\u0647\u0645 \u062a\u0635\u0631\u064a\u062d')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>المعتمرين الذين لم يصدر لهم تصريح</value>
        <webElementGuid>077c744e-1b75-4abd-9276-c812ad63f0ce</webElementGuid>
    </webElementProperties>
</WebElementEntity>