<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c9c7e44f-50c0-44f3-a820-f8a3ea453ca0</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_qa_menu_groups</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="kt-menu__item\\ \\ kt-menu__item--submenu"] &gt; #qa-menu-groups</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'qa-menu-groups') and equals(@text,'Groups Management')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>qa-menu-groups</value>
        <webElementGuid>077c744e-1b75-4abd-9276-c812ad63f0ce</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Groups Management</value>
        <webElementGuid>077c744e-1b75-4abd-9276-c812ad63f0ce</webElementGuid>
    </webElementProperties>
</WebElementEntity>