<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>124864e6-f9b4-4c55-b93d-d021fdf8ac8f</elementGuidId>
    <imagePath></imagePath>
    <name>button_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[2]/div[1]/div[1]/div[2]/form[1]/div[1]/div[3]/div[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\\ btn-outline-danger-\\ mr-3"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'reset') and equals(@text,'\u0645\u0633\u062d \u0627\u0644\u062a\u0635\u0641\u064a\u0629')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>مسح التصفية</value>
        <webElementGuid>11ed2f2a-a590-4328-a925-d9589ad282f0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>reset</value>
        <webElementGuid>11ed2f2a-a590-4328-a925-d9589ad282f0</webElementGuid>
    </webElementProperties>
</WebElementEntity>