<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bfd93cbb-c58e-412b-aa65-83db8aa5f190</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_qa_create_package</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="dropdown-menu\\ dropdown-menu-fit\\ dropdown-menu-right\\ show"] #qa-create-package</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'qa-create-package') and equals(@text,'\u0625\u0646\u0634\u0627\u0621 \u0628\u0631\u0646\u0627\u0645\u062c')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>qa-create-package</value>
        <webElementGuid>077c744e-1b75-4abd-9276-c812ad63f0ce</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>إنشاء برنامج</value>
        <webElementGuid>077c744e-1b75-4abd-9276-c812ad63f0ce</webElementGuid>
    </webElementProperties>
</WebElementEntity>