<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3cb3596d-5924-4aa0-a622-04088f094dde</elementGuidId>
    <imagePath></imagePath>
    <name>button_review</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[5]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\\ btn-primary\\ mt-32"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'review') and equals(@type,'button') and equals(@text,'\u0645\u0631\u0627\u062c\u0639\u0629 \u0627\u0644\u062c\u0648\u0627\u0632')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>review</value>
        <webElementGuid>3cce3c2c-2fc7-4509-beee-8337578025c3</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>مراجعة الجواز</value>
        <webElementGuid>3cce3c2c-2fc7-4509-beee-8337578025c3</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>3cce3c2c-2fc7-4509-beee-8337578025c3</webElementGuid>
    </webElementProperties>
</WebElementEntity>